type: object
properties:
  enabled:
    type: boolean
    description: If MFA method is enabled.
  host:
    type: string
    description: The server host name or IP address of the MFA provider.
    example: example.com
  accessKey:
    type: string
    description: The secret key for authenticating requests to the MFA provider.
  identityAttribute:
    type: string
    description: Optional. The name of the attribute for mapping IdentityNow identity to the MFA provider.
    example: email
